exports.EMPTY_GUID = "00000000-0000-0000-0000-000000000000";
exports.UserServiceIndex = {
	GSI1NAME: "Session-index",
	GSI1KEYS :{
		PK: "Session"
	},
	GSI2NAME:"Email-index",
	GSI2KEYS:{
		PK:"Email"
	}
};
exports.UserEventCode = {
    CREATE:"CREATE",
	LOGIN:"LOGIN",
	LOGOUT: "LOGOUT",
    ENROLL:"ENROLL",
    UNENROLL:"UNENROLL",
    CHANGEPASSWORD:"CHGPASS",
    UPDATEPROFILE:"UPDPRO",
    SUBSCRIBE:"SUB",
    UNSUBSCRIBE:"UNSUB",
    CHANGESUBSCRIBTION:"CHGSUB",
    ACTIVATE:"ACT",
	DEACTIVATE: "DEACT"
};
exports.ResponseCode={
	"UNAUTHORISED":"401",
	"RESOURCE_NOT_FOUND":"404",
	"TIMEOUT":"504",
	"BAD_REQUEST_BODY":"402",
	"BAD_REQUEST_PARAMETERS":"405",
	"ACCESS_DENIED":"403",
	"SUCCEED_NO_CONTENT":"204",
	"SUCCEED_OK":"200",
	"SUCEED_ACCEPTED":"202",
	"NOT_IMPLEMENTED":"501",
	"SERVICE_REQUEST_FAILURE":"500"

}
